### ISSUE TITLE
Support for M1 macOS GitHub Actions runners

### ISSUE THREAD

**Issue by aitorct** [phrase/setup-cli#18]
`phrase/setup-cli@v1` breaks in M1 macOS GitHub Actions runners. I tried with versions `2.15.0` (latest) and `2.3.0`.

![Error](https://github.com/phrase/setup-cli/assets/6463569/3891d3bb-5b07-43a6-8cbd-c12ceb97afdd)

## Demo workflow
```yml
name: Phrase test

on:
  pull_request:

jobs:
  phrase-test:
    name: Phrase test
    runs-on: macos-13-xlarge

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Phrase
        uses: phrase/setup-cli@v1
        with:
          version: 2.15.0
      - name: Phrase pull 
        run: phrase pull
```

Switching back to an Intel-based runner makes it work.

```diff
-    runs-on: macos-13-xlarge
+    runs-on: macos-13-large
```
